FROM python:3.11.2-alpine

WORKDIR /usr/src/app

COPY django/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY django .

ENTRYPOINT [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
